-- Plugins
require("config.plugins.lsp")
require("config.plugins.mason")
require("config.plugins.cmp")
require("config.plugins.treesitter")
require("config.plugins.lualine")
require("config.plugins.nvimtree")
require("config.plugins.trouble")
require("config.plugins.bufferline")
require("config.plugins.telescope")
require("config.plugins.formatter")
require("config.plugins.blankline")
require("config.plugins.notifications")
require("config.plugins.comment")
require("config.plugins.git")
